import React, { useState, useEffect } from "react";
import { Row, Col, Card } from "antd";
import axios from "axios";
import TabelaUsuarios from "@/components/TabelaUsuarios";
import TabelaArtigos from "@/components/TabelaArtigos";
import NavAdmin from '@/components/NavAdmin'
import Head from 'next/head'

function Principal(props) {
  const [artigos, setArtigos] = useState([]);
  const [usuarios, setUsuarios] = useState([]);

  useEffect(() => {
    fetchData();
    fetchDataArtigos();
  }, []);

  const fetchData = async (filtro) => {
    try {
      const usuarios = await axios.get("http://localhost:4000/user/consultar", { params: { filtro } });
      setUsuarios(usuarios.data);
    } catch (error) {
      console.error("Erro ao obter dados:", error.message);
    }
  };

  const fetchDataArtigos = async (filtro) => {
    try {
      const artigos = await axios.get("http://localhost:4000/article/consultar", { params: { filtro } });
      setArtigos(artigos.data);
    } catch (error) {
      console.error("Erro ao obter dados:", error.message);
    }
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
      </div>
      <Card>
        <Row gutter={[10, 10]}>
          <Col span={24}>
            <TabelaUsuarios usuarios={usuarios}
              onFilterChange={(filtro) => fetchData(filtro)}
              onUsuariosChange={fetchData} />
          </Col>
          <Col span={24}>
            <TabelaArtigos artigos={artigos}
              onFilterChange={(filtro) => fetchDataArtigos(filtro)}
              onArtigosChange={fetchDataArtigos} />
          </Col>
        </Row>
      </Card>
    </>
  )
}
export default Principal;