import React, { useState, useEffect } from "react";
import { Row, Col, Card } from "antd";
import axios from "axios";
import TabelaUsuarios from "@/components/TabelaUsuarios";
import TabelaArtigos from "@/components/TabelaArtigos";
import NavAdmin from '@/components/NavAdmin'
import MenuUsers from '@/components/MenuUsers';
import Head from 'next/head'
import Link from 'next/link'

function Principal(props) {
  const [artigos, setArtigos] = useState([]);
  const [usuarios, setUsuarios] = useState([]);

  useEffect(() => {
    // Chamada à API para obter dados
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const usuario = await axios.get("http://localhost:4000/user/consultar");
      setUsuarios(usuario.data);
    } catch (error) {
      console.error("Erro ao obter dados:", error.message);
    }
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
      </div>
      <Card>
        <Row gutter={[10, 10]}>
          <Col span={24}>
            <TabelaUsuarios usuarios={usuarios}
              onUsuariosChange={fetchData} />
          </Col>
          <Col span={24}>
            <TabelaArtigos />
          </Col>
        </Row>
      </Card>
    </>
  )
}
export default Principal;