// import ArticleList from '@/components/ArticlesList'
import React from "react";
import { Col, Row } from "antd";
import NavHome from '@/components/NavHome'
import Head from 'next/head'
import TabelaCurtidos from "@/components/TabelaCurtidos";
import TabelaDestaque from "@/components/TabelaDestaque";

export default function Home() {
  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavHome />
      </div>

      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
              <h3> Lista de Artigos Destaque</h3>
              <TabelaDestaque />
              {/* <ArticleList></ArticleList> */}
          </div>
          <div className="row border-bottom">
              <h3> Lista de Artigos mais Curtidos</h3>
              <TabelaCurtidos/>
              {/* <ArticleList></ArticleList> */}
          </div>
          <div className="row border-bottom">
              <h3> Buscador de Artigos</h3>
              <div className="input-group">
                  <input type="text" className="form-control" placeholder="Palavra-chave" aria-describedby="button-busca" />
                  <button className="btn btn-outline-secondary" type="button" id="button-busca">Buscar</button>
              </div>
          </div>
        </div>
      </div>  
  </>
  )
}


