// import ArticleList from '@/components/ArticlesList'
import React from "react";
import { Card, Col, Row, Input, Button } from "antd";
import { SearchOutlined } from '@ant-design/icons';
import NavHome from '@/components/NavHome'
import Head from 'next/head'
import TabelaCurtidos from "@/components/TabelaCurtidos";
import TabelaDestaque from "@/components/TabelaDestaque";

export default function Home() {
  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavHome />
      </div>
      <Card title="Login"
        style={{
          width: 1250,
          margin: 'auto',
          marginTop: 10,
        }}>
        <Row gutter={[10, 10]}>
          <Col span={24}>
            <TabelaDestaque />
          </Col>
          <Col span={24}>
            <TabelaCurtidos />
          </Col>
        </Row>
      </Card>
    </>
  )
}


