import React from 'react';
import { Form, Input, Button, Card, Row, Col, message } from 'antd';
import Head from 'next/head';
import { useRouter } from 'next/router';
import axios from 'axios';

export default function Home() {
  const [mensagem, contextHolder] = message.useMessage();
  const router = useRouter();

  const onFinish = async (values) => {
    try {
      const response = await axios.post('http://localhost:4000/user/login', {
        author_user: values.usuario,
        author_pwd: values.senha,
      });

      if (response.data.authenticated) {
        router.push('/admin/principal/Principal');
      } else {
        mensagem.open({
          type: 'error',
          content: `Autenticação falhou`,
        })
      }
    } catch (error) {
      mensagem.open({
        type: 'error',
        content: `Sem permissão!`,
      })
    }
  };

  const onFinishFailed = (errorInfo) => {
    mensagem.open({
      type: 'error',
      content: `Erro: ${errorInfo}`,
    })
  };

  return (
    <>
    {contextHolder}
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Card title="Login"
        style={{
          width: 500,
          margin: 'auto',
          marginTop: '10%',
          textAlign: 'left',
        }}>
        <Form layout="vertical"
          onFinish={onFinish}
          onFinishFailed={onFinishFailed}>
          <Row gutter={[10, 10]}>
            <Col span={24}>
              <Form.Item name="usuario"
                label="Usuário"
                rules={[{ required: true, message: 'Por favor, insira o nome do usuário' }]} >
                <Input />
              </Form.Item>
            </Col>
            <Col span={24}>
              <Form.Item name="senha"
                label="Senha Login"
                rules={[{ required: true, message: 'Por favor, insira a senha do usuário' }]} >
                <Input.Password />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item>
                <Button block
                  href="/">
                  Voltar
                </Button>
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item>
                <Button type='primary'
                  block
                  htmlType="submit">
                  Logar
                </Button>
              </Form.Item>
            </Col>
          </Row>
        </Form>
      </Card>
    </>
  );

}