import React from 'react';
import { Form, Input, Button, Card, Row, Col } from 'antd';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();

  const onFinish = (values) => {
    // Adicione a lógica de autenticação aqui
    console.log('Received values:', values);

    // Exemplo de navegação para outra página após a autenticação
    router.push('/admin/principal/Principal');
  };

  const onFinishFailed = (errorInfo) => {
    console.log('Failed:', errorInfo);
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Card title="Login"
        style={{
          width: 300,
          margin: 'auto',
          marginTop: '10%',
        }}>
        <Form layout="vertical"
          onFinish={onFinish}
          onFinishFailed={onFinishFailed}>
          <Row gutter={[10, 10]}>
            <Col span={24}>
              <Form.Item name="usuario"
                label="Usuário"
                rules={[{ required: true, message: 'Por favor, insira o nome do usuário' }]} >
                <Input />
              </Form.Item>
            </Col>
            <Col span={24}>
              <Form.Item name="senha"
                label="Senha Login"
                rules={[{ required: true, message: 'Por favor, insira a senha do usuário' }]} >
                <Input.Password />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item>
                <Button block
                  href="/">
                  Voltar
                </Button>
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item>
                <Button type='primary'
                  block
                  htmlType="submit">
                  Logar
                </Button>
              </Form.Item>
            </Col>
          </Row>
        </Form>
      </Card>
    </>
  );
}